### ISSUE TITLE
The log level of the currency service contains an invalid value

### ISSUE THREAD

**Issue by gamunu** [GoogleCloudPlatform/microservices-demo#1274]
### Describe the bug 
The log level of the currency service contains an invalid value (a number). This should contain values INFO, DEBUG...

### To Reproduce 

deploy the application on any k8s cluster

currencyservice:v0.4.1

### Logs  
```json
{   "level": 30,   "time": 1668759260143,   "pid": 1,   "hostname": "currencyservice-xxx",   "name": "currencyservice-server",   "message": "conversion request successful" }


{   "level": 30,   "time": 1668759260139,   "pid": 1,   "hostname": "currencyservice-xxxx",   "name": "currencyservice-server",   "message": "Getting supported currencies..." }
```

### Screenshots 

<img width="993" alt="Screenshot 2022-11-18 at 13 50 59" src="https://user-images.githubusercontent.com/4501687/202655491-e460fc3d-b1a8-490e-b254-8273e4ae7ca8.png">

### Environment 

Linux

AWS (EKS)

containerd (v1.6.10)

### Exposure 

persistent

**Comment by NimJay** [comment]
I believe the reason for this is because pino's [`useLevelLabel` option is deprecated](https://github.com/pinojs/pino/issues/848).
I will work on fixing this.
I believe the change is as simple as using `pino`'s new [`formatter` option](https://github.com/pinojs/pino/blob/master/docs/api.md#formatters-object):
```javascript
...
const logger = pino({
  name: 'paymentservice-server',
  messageKey: 'message',
  formatters: {
    level (logLevelString, logLevelNum) {
      return { severity: logLevelString }
    }
  }
});
...
```

Thank you for reporting this issue, @gamunu! :)
