### ISSUE TITLE
cartservice: proposal to make `ssl` flag configurable 

### ISSUE THREAD

**Issue by askmeegs** [GoogleCloudPlatform/microservices-demo#141]
The redis connection ssl flag for cartservice is currently hardcoded to `false`.        

https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/src/cartservice/cartstore/RedisCartStore.cs#L47

In order to get cartservice working with `STRICT` Istio mTLS, it might make sense to make this configurable. 

Beyond the bool flag, not sure if we'd need other library-specific ssl config, like `sslHost`. https://stackexchange.github.io/StackExchange.Redis/Configuration

**Comment by simonz130** [comment]
We can make it configurable, but we also need to know which cert to use for SSL - for cases when the flag is true. 
I don't have cycles short term to investigate, but if you tell me, it will speed up coding :)

**Comment by ahmetb** [comment]
Doesn’t istio have transparently add/terminate mTLS in this case?

Assuming client gets its cert/key from an Istio volume mount, how does the server verify the client? I am assuming the server needs to know (1) the ca cert (2) the client cert which comes in the request.

And since the client identity changes frequently, I assume we can’t just encode into redis which client cert to accept?
