### ISSUE TITLE
The link [go/microservices-demo](http://go/microservices-demo) gave me "This site can’t be reached" error.

### ISSUE THREAD

**Issue by briansu2004** [GoogleCloudPlatform/microservices-demo#1437]
### Describe the bug 

The link [go/microservices-demo](http://go/microservices-demo) doesn't work to me. 

I tried http://go.google.com/microservices-demo and got the same error "This site can’t be reached".

👓Note to Googlers: Please fill out the form at [go/microservices-demo](http://go/microservices-demo) if you are using this application.

### To Reproduce 

https://github.com/GoogleCloudPlatform/microservices-demo

### Screenshots 

![image](https://user-images.githubusercontent.com/6775994/210184994-4634a0b2-f5ca-4237-ac80-567288a66cc4.png)

![image](https://user-images.githubusercontent.com/6775994/210185017-bc37fc0b-0087-4095-ba41-542a9923faa4.png)

**Comment by NimJay** [comment]
Hi @briansu2004,

That link/form (http://go/microservices-demo) is only supposed to work for Googlers (Google employees).
We currently do not have a similar form for non-Googlers because we cannot easily survey non-Googlers (without approval from a privacy and data team).

If you are a Googler yourself, feel free to ping me via Google Chat or email me, and I can share the link to the form. :)

Let me know if you have additional questions. Thanks!

### Additional Info
* "go/" links are used internally by Google, Twitter, and many other organizations to shorten URLs. [Source.](https://golinks.github.io/golinks/)

**Comment by briansu2004** [comment]
👍 😊
