### ISSUE TITLE
Support `skaffold debug` for at least 1 microservice

### ISSUE THREAD

**Issue by JayDew** [GoogleCloudPlatform/microservices-demo#1460]
### Write down your inquiry 

I am successfully running the application, hats down to all the contributors!

However, I cannot figure out how to debug the application.

I lunch the Kubernetes cluster using Cloud Code plug-in for IntelliJ (Ultimate 2022.3.1), but none of the breakpoints are hit.

Anyone knows what needs to be configured? Or any tips to debug it?

Thanks

**Comment by gitsan13** [comment]
Hi @JayDew 
I would love to give this issue a try:)
Can you please assign me to it?

**Comment by NimJay** [comment]
Hi @JayDew,
1. Did you follow the instructions in the [`development-guide.md`](https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/docs/development-guide.md#option-2---local-cluster)?
2. If you followed the instructions in [`development-guide.md`](https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/docs/development-guide.md#option-2---local-cluster), did you try `skaffold dev` instead of `skaffold run`?
3. What specifically are you interested in debugging? If you'd like to use breakpoints for the source code of a microservice, unfortunately, Online Boutique doesn't have a documented way of setting breakpoints for its microservices.

**Comment by JayDew** [comment]
Hello @NimJay 

3. I am new to microservices, and I am curious about how modularity impacts development (compared to a monolith)
**Therefore, it would be nice for this demo application to provide clear instructions on how to debug the code**

1 . I first got the cluster running by following the instructions in the local development guide
    I then installed Cloud Code, as per [Skaffold documentation](https://skaffold.dev/docs/workflows/debug/):

> The easiest way to debug using Skaffold is by using the Cloud Code IDE extension for Visual Studio Code, JetBrains IDEs, and Cloud Shell. Cloud Code will automatically configure container images for debugging so you can debug Kubernetes services just like how you would debug a local service in your IDE.

2. skaffold dev cannot be used for debugging

**Comment by JayDew** [comment]
@gitsan13 I appreciate your effort! I am afraid I cannot change the assignees :(

**Comment by NimJay** [comment]
Thanks for your quick and clear response, @JayDew. 

I am not familiar with `skaffold debug` so thanks for linking to the [documentation](https://skaffold.dev/docs/workflows/debug/).
But wow, this would 100% a good feature to have on Online Boutique — for at least 1 microservice (ideally, the `frontend` service).
Unfortunately, none of the maintainers (including myself) have used `skaffold debug` before.

I will keep this GitHub issue open and update the title to "Support skaffold debug" since this is an important user journey.

@JayDew and @gitsan13, in the meantime, if you have any luck with `skaffold debug`-ing any of Online Boutique's microservices, feel free to share your experience in this GitHub issue.

**Comment by praveen-emsec** [comment]
Hello @JayDew @NimJay ,I am also new to the microservices i support the fact as you said @JayDew that th repo should have details for debugging also i suppose you are facing this issue while running the **skaffold** run command 
Error says,
running -> **./skaffold run**
**WARN[0000] Your Skaffold version might be too old. Download the latest version (2.6.0) from:
  https://github.com/GoogleContainerTools/skaffold/releases/tag/v2.6.0 
parsing skaffold config: error parsing skaffold configuration file: unknown skaffold config API version "skaffold/v4beta6". Set the config 'apiVersion' to a known value. Check https://skaffold.dev/docs/references/yaml/ for the list of valid API versions. Otherwise, check that your skaffold version is up-to-date.**

**Comment by praveen-emsec** [comment]
tell me if you have any solution for this, I am trying to builf this up,
Thanks

**Comment by bourgeoisor** [comment]
Considering this issue is now quite old, I'll be closing it. Skaffold has been upgraded throughout the repo over the past year, and some of the information in this thread is likely out of date. Feel free to reopen if you try again with the current state of the repo and still running into issues.
