### ISSUE TITLE
proposal: provide istio mTLS resources

### ISSUE THREAD

**Issue by askmeegs** [GoogleCloudPlatform/microservices-demo#184]
Currently the manifests in `release/istio-manifests.yaml` are designed for `PERMISSIVE` mTLS authentication.

If the user sets mTLS is set to `STRICT` for either the Hipstershop service(s), globally, or for the namespace in which Hipstershop is ,  `frontend` (and potentially other services) will not start up due to the Liveness/Readiness probes. 

I propose we create Istio manifests for both PERMISSIVE and STRICT mTLS -- and instruct users to use the PERMISSIVE manifests by default. 

See [Bookinfo](https://github.com/istio/istio/tree/master/samples/bookinfo/networking) for an example of how we might separate out the manifests.

**Comment by ahmetb** [comment]
I'm erring on the side of simplicity here and as long as we're showing the PERMISSIVE mode well, the rest can be left as an exercise for the reader.

Given we support N products in this demo and each product had M set up options, we'd end up with M*N installation options, which is not scalable. If we can keep the demo app to support only PERMISSIVE (and maybe add a paragraph on how STRICT can be made to work, like we do in the readme right now), that would be a better choice.

Adding multiple yaml files not only would break install instructions, it would create so much trouble for the existing release scripts.

**Comment by davidebbo** [comment]
I just noticed the readme has:

   > NOTE: If you need to enable `MTLS_STRICT` mode, you will need to update
   > several manifest files:
   >
   > - `kubernetes-manifests/frontend.yaml`: delete "livenessProbe" and
   >   "readinessProbe" fields.
   > - `kubernetes-manifests/loadgenerator.yaml`: delete "initContainers" field.

Maybe that's good enough, assuming those instructions are correct and get you into a working state with STRICT.

**Comment by davidebbo** [comment]
I guess the part that's a little bit confusing is that the readme doesn't really cover the 'Pre-Built Container Images' + Istio scenario. In this scenario, you'd use `release/istio-manifests.yaml` and `release/kubernetes-manifests.yaml`, and you'd need to make the above changes to `kubernetes-manifests.yaml` instead of to the individual files.

And side note: in this scenario, you'd also want to delete the `frontend-external` service, as it's not used with Istio.

**Comment by ahmetb** [comment]
> And side note: in this scenario, you'd also want to delete the `frontend-external` service, as it's not used with Istio.

Fair point, but this would result in a far more engineered release script. Right now all of frontend stuff is in a `frontend.yaml` and we'd have to split them out to different files.

Similarly, this wouldn't work with skaffold well (we'd have to duplicate the skaffold.yaml file for this case). So I foresee some overengineering there just to handle this case.

> the readme doesn't really cover the 'Pre-Built Container Images' + Istio scenario

That's mostly because of the N*M problem above. 

- "Building from source" vs "using pre-built images"
- Istio vs "no Istio"
  - Strict vs Permissive

is creating so many installation paths, making it complicated for everyone to use. That's primarily why I'm thinking we should leave stuff like STRICT mode as an exercise to the reader (or just document it).

**Comment by davidebbo** [comment]
Fair enough. Maybe just add a quick note in the readme section I quoted above that when people are using pre-built images, the changes need to go into `release/kubernetes-manifests.yaml` instead of the individual files.

**Comment by offdarecord** [comment]
> I just noticed the readme has:
> 
> > NOTE: If you need to enable `MTLS_STRICT` mode, you will need to update
> > several manifest files:
> > 
> > * `kubernetes-manifests/frontend.yaml`: delete "livenessProbe" and
> >   "readinessProbe" fields.
> > * `kubernetes-manifests/loadgenerator.yaml`: delete "initContainers" field.
> 
> Maybe that's good enough, assuming those instructions are correct and get you into a working state with STRICT.

So far, I've followed these instructions with MTLS_STRICT and commented out the sections of the manifest files mentioned above. I'm yet to have a successful install, and keep getting "no healthy upstream" message displayed.

**Comment by therealmitchconnors** [comment]
> I'm yet to have a successful install, and keep getting "no healthy upstream" message displayed.

@offdarecord, can you give us more information about your environment?  In particular, what version of Istio are you using, and where are you seeing the "no healthy upstream" message?

**Comment by therealmitchconnors** [comment]
@ahmetb the frontend liveness and readiness probes can work with Istio/mTLS if the helm install command for instio includes --set sidecarInjectorWebhook.rewriteAppHTTPProbe=true

This enables the sidecar injector to rewrite the HTTP probes to point to Envoy's proxied readiness endpoint.

I am investigating modifications that would allow the loadgenerator to wait for frontend to become available without the use of an init container (which may be problematic for Istio/mTLS because the istio-proxy is not yet running to wrap the call in mTLs).  This would involve adding curl to the loadgenerator image, and moving the curl command from the init container into the main.  Would this be acceptable?  It should work with or without Istio/mTLS...

**Comment by ahmetb** [comment]
@therealmitchconnors It's agreeable to modify the loadgenerator, as long as it works on most Istio installations, and doesn't impact the non-Istio installations.

> --set sidecarInjectorWebhook.rewriteAppHTTPProbe=true

I think this is not a realistic expectation, as we primarily suggest users to try this out with GKE Istio add-on where they can't customize such values.

Right now I'm totally OK with documenting "if you want strict mTLS, remove the probes", but as you suggested if there's something that reduces the steps without overcomplicating it, happy to accept

**Comment by therealmitchconnors** [comment]
> we primarily suggest users to try this out with GKE Istio add-on where they can't customize such values.

For existing deployments, such as Istio on GKE, the way to rewrite probes is to modify the istio-sidecar-injector configmap to set rewriteAppHTTPProbe to true.  The primary complication there is that this value appears to have been added in 1.1, and I assume you would like to allow 1.0.x deployments (such as Istio on GKE).

I will investigate the viability of this feature on releases back through whatever Istio on GKE is using.

**Comment by askmeegs** [comment]
Readiness and liveness probes should now work with istio mTLS. 

Will address in: https://github.com/GoogleCloudPlatform/microservices-demo/issues/211
