### ISSUE TITLE
How about add new service which is written by PHP?

### ISSUE THREAD

**Issue by taka2noda** [GoogleCloudPlatform/microservices-demo#1847]
### Describe request or inquiry 
I think it would be worth adding new service which is written by PHP.

### What purpose/environment will this feature serve? 
The main reasons are like below.
1. There is no service which is configured by PHP. https://github.com/GoogleCloudPlatform/microservices-demo#architecture
2. PHP will be supported by OTel - current status is beta. https://opentelemetry.io/docs/instrumentation/php/

Thank you.

**Comment by bourgeoisor** [comment]
cc: @NimJay

**Comment by NimJay** [comment]
Thanks for this feature request (and heads-up), @taka2noda! :)
It's a good idea!
However, even though showcasing OpenTelemetry is _part_ of [Online Boutique's purpose](https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/docs/purpose.md), it's a large engineering that we, unfortunately, won't be able to prioritize and put effort into in the near future. Thus, I will close this issue. Sorry about that.

As a next step, consider creating a GitHub issue inside https://github.com/open-telemetry/opentelemetry-demo — which is a fork of _this_ repo (microservices-demo/Online Boutique) but more centered around OpenTelemetry.
CC: @arbrown

Fun fact: The initial plan (from 2008) for microservices-demo proposed a PHP microservice, but we scrapped it because PHP expertise was scarce on our team at the time (CC: @grayside).

**Comment by taka2noda** [comment]
Hi @NimJay. 
Thank you for your detailed explanation. While it's unfortunate, I understand now.
