### ISSUE TITLE
grpc probes component missing

### ISSUE THREAD

**Issue by yogeek** [GoogleCloudPlatform/microservices-demo#1891]
### Describe the bug 
GRPC probes are enabled by default 
the [kustomize README](https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/kustomize) mentions a component to [enable GRPC probes](https://github.com/GoogleCloudPlatform/microservices-demo/blob/v0.8.0/kustomize/components/native-grpc-health-check) but it is missing

### To Reproduce 
deploy the 0.8.0 on a 1.23 k8s cluster => pod probes are GRPC but incompatible with a <1.24 cluster

**Comment by NimJay** [comment]
Hi @yogeek,

Thanks for reporting this issue! :)
Unfortunately, Online Boutique (as of [v0.8.0](https://github.com/GoogleCloudPlatform/microservices-demo/releases/tag/v0.8.0)) no longer includes the [grpc-health-probe binary](https://github.com/grpc-ecosystem/grpc-health-probe). Online Boutique's gRPC microservices rely on the gRPC health-check probes that are built into Kubernetes.

I will correct the docs in via https://github.com/GoogleCloudPlatform/microservices-demo/pull/1893.
We made this decision because: 
* on 2023 April 7, Stable GKE clusters using 1.23 were auto-upgraded to 1.24. See [schedule for release channels](https://cloud.google.com/kubernetes-engine/docs/release-schedule#schedule-for-release-channels).
* the [end of life for GKE 1.23 is 2023 July 31](https://cloud.google.com/kubernetes-engine/docs/release-schedule#schedule-for-release-channels).
* one of the primary purposes of this repo is to showcase GKE

Sorry for the inconvenience! If you really need to use Kubernetes 1.23 or lower, you might be able to [use Online Boutique v0.7.0](https://github.com/GoogleCloudPlatform/microservices-demo/tree/v0.7.0) or lower. But I discourage using older versions of Online Boutique, because we don't provide active support for older versions.
```
git fetch --all --tags
git checkout tags/v0.7.0
```
Note: That ["native-grpc-health-check" Kustomize component](https://github.com/GoogleCloudPlatform/microservices-demo/tree/v0.7.0/kustomize/components/native-grpc-health-check) **is not** what you need. That component _removes_ the [grpc-health-probe binary](https://github.com/grpc-ecosystem/grpc-health-probe) and uses built-in Kubernetes probes. What you're looking for is the default (base) deployment of 0.7.0 or older.

Hope this helps.
Thanks again!

**Comment by yogeek** [comment]
Thank you for your help @NimJay 👍
I'll try to patch the 0.8.0 probes with kustomize to make it compatible with K8s 1.23 until we upgrade to 1.24.
