### ISSUE TITLE
Consider moving demo.proto to pb/hipstershop

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/microservices-demo#20]
Very much related to issue #1.

It seems like we'll soon end up with:

```
pb
├── demo.proto  <-- this doesn't look good here
├── googleapis
│   └── types
│       └── money.proto
└── grpc
    └── health
        └── v1
            └── health.proto
```

Therefore we should consider moving Hipster Shop related proto(s) to their own directory.

**Comment by jan25** [comment]
@ahmetb would you know if someone is already working on this? Otherwise, I can pick this up

**Comment by ahmetb** [comment]
Nobody’s working on it. 

So the structuring is definitely one aspect. Another one is how to generate them, like what’s the best practice to host .pb files in a repo and generate code from them without writing too many bash scripts for it.

**Comment by jan25** [comment]
We could split `demo.proto` into multiple `.proto` files, and put each one within respective directory for a particular service. All these directories will still sit in top level `pb` directory in this repo.

Additionally, we need one script that takes a argument such as `--output-language`, this script then generates one source code file per `.proto` file after going through all available `.proto` files.

This script is meant to be invoked from within a service implementation directory(or repository) so the generated code is put in a subdirectory like `/proto`. So, we may need to change how we currently generate and use pb source code in all of services(since they are differently done depending on service implementation lang/build process). Also, we will need multiple import statements to import individual pb modules in source code unlike single import as we currently have.

As a bonus for the script, we could have additional argument like `--dependencies` to specify service dependencies so only required pb source files that are actually needed for a service are copied(or pulled) into `/proto` subdirectory

**Comment by askmeegs** [comment]
Closing in favor of https://github.com/GoogleCloudPlatform/microservices-demo/issues/1
