### ISSUE TITLE
One artifact seems to be missing (recommendationservice 0.3.6) in gcr.io

### ISSUE THREAD

**Issue by djazayeri** [GoogleCloudPlatform/microservices-demo#2367]
I installed the microservices demo, and all service and workloads start fine, _except_ for:

`Cannot pull image 'gcr.io/google-samples/microservices-demo/recommendationservice:v0.3.6' from the registry.`

**Comment by NimJay** [comment]
Hi @djazayeri!

**1.**  Repushed images `recommendationservice:v0.3.6`
Unfortunately, we don't have audit logs around Container Registry write operations to know why that image was deleted.
My guess is that it was removed (either automatically or manually) due to vulnerability count.
I've rebuilt and repushed the image. **You should be unblocked now.**
Fortunately, the vulnerability count of this particular image should be lower than before (IDK what the old vuln. count was), since today's rebuild used a new version of [python:3.7-slim](https://github.com/GoogleCloudPlatform/microservices-demo/blob/release/v0.3.6/src/recommendationservice/Dockerfile#L15).

**2.** Avoid using `v0.3.6` and other old versions
`v0.3.6` is a very old version of Online Boutique.
**Question:** Could you share a link to the piece of content that's using `v0.3.6`?
We should work towards updating the images and YAML manifests to the latest version.
Unfortunately, we only have automated tests for whatever's on `main`.

Sorry for the inconvenience.
Hope this helps. Thanks!

**Comment by djazayeri** [comment]
I was following https://cloud.google.com/service-mesh/docs/onlineboutique-install-kpt. I will ask to get that updated to use the latest microservices-demo.

(Offhand do you know if there's anything non-trivial in updating those docs to use the latest?)

**Comment by NimJay** [comment]
Thanks for sharing the source (the [Deploying the Online Boutique sample application](https://cloud.google.com/service-mesh/docs/onlineboutique-install-kpt) tutorial).

> Offhand do you know if there's anything non-trivial in updating those docs to use the latest?

Good question.

1. I believe the main differences between this repo default Online Boutique deployment and `anthos-service-mesh-packages's Online Boutique deployment:
    * `anthos-service-mesh-packages` deploys each microservice into its own namespace; while _this_ repo deploys all microservices to the default namespace.
    * `anthos-service-mesh-packages` creates and assigns each microservice its own ServiceAccount while _this_ repo uses the default ServiceAccount for all microservices (unless you explicitly opt into the [this repo's ServiceAccount Kustomize Component](https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/kustomize/components/service-accounts))

2. Between 0.3.6 and 0.9.0, the YAML definitions for the `Deployment` resources changed (to keep up with current versions of GKE/Kubernetes).

I'm happy to create the pull-request to update Online Boutique at https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages.

**Comment by NimJay** [comment]
Pull-request to update that tutorial to use v0.9.0: https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/pull/1575
