### ISSUE TITLE
Running GKE in Cloud Shell Fails

### ISSUE THREAD

**Issue by cswingle-google** [GoogleCloudPlatform/microservices-demo#2378]
### Describe the bug 
Following directions at https://github.com/GoogleCloudPlatform/microservices-demo?tab=readme-ov-file#interactive-quickstart-gke to run in cloud shell fails with https://screenshot.googleplex.com/8vThxTFfKtU5JU6.

### To Reproduce 
1. Open in Google Cloud Shell
2. Allow access to run.

### Logs  
Failure:
```
dsexec: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by dsexec)
dsexec: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by dsexec)
dsexec: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by dsexec)
dsexec: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by dsexec)
```

### Screenshots 
https://screenshot.googleplex.com/8vThxTFfKtU5JU6

**Comment by NimJay** [comment]
@cswingle-google, thanks so much for reporting this issue.

Based on my very brief investigation, this seems like an issue with DeployStack (@tpryan) and has been reported at https://github.com/GoogleCloudPlatform/deploystack/issues/173. Online Boutique leverages DeployStack to support that one-click deployment button.

Alternatively you could try:
1. Deploying Online Boutique (and a GKE cluster) via `gcloud` and `kubectl` commands via the [quickstart inside /README.md](https://github.com/GoogleCloudPlatform/microservices-demo?tab=readme-ov-file#quickstart-gke).
2. Deploying Online Boutique (and a GKE cluster) via the [Terraform inside /terraform](https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/terraform#use-terraform-to-deploy-online-boutique-on-a-gke-cluster).
3. The Jump Start Solutions called [Ecommerce web application deployed on Kubernetes](https://console.cloud.google.com/products/solutions/details/ecomm-microservices), which is a much more complex version of Online Boutique.

I'll remove that one-click deployment button until this issue is resolved: https://github.com/GoogleCloudPlatform/microservices-demo/pull/2379

**Comment by bourgeoisor** [comment]
Closing as resolved. Feel free to reopen if you're still running into issues.
