### ISSUE TITLE
hipstershop should have at least one http service apart from frontend.

### ISSUE THREAD

**Issue by mandarjog** [GoogleCloudPlatform/microservices-demo#358]
At present only `frontend` is the http1.1 service. This is not a typical customer. We expect customers to have many http1.1 and a few grpc or 50-50.
This application is widely used in service mesh demos.

1. Convert one service to http
2. Or give the ability to deploy a grpc service as http and update clients accordingly.

**Comment by mandarjog** [comment]
@askmeegs

**Comment by ahmetb** [comment]
This has previously crossed my mind at the time of development. We could consider exposing a JSON REST API over HTTP. It doesn’t have to be large. Could be as simple as /api/products to return the catalog —and can be called apifrontend.

**Comment by mandarjog** [comment]
Will that only expose one more service over http ?
Should be preferably two services,  but we can start with one.

**Comment by ahmetb** [comment]
I miss the point of more than two HTTP frontends. If you need it, you can just copy the frontend and make clones of it with different names.

The architecture represents a single app, so I’m not entirely sure when someone looks at this app they will say “I have 5 HTTP services, so this demo app is not useful for me”. 

I am not sure this is something we “should” do, as it creates long-term maintenance burden.

Also keep in mind adding even 1 service will break dozens of tutorials and solutions and codelabs that use this project. Istio team isn’t the only user of this. :)

**Comment by prune998** [comment]
We forked the (old) hipstershop and put some huge changes in it. Like supporting Zipking and Jaeger.
I also re-wrote the `adservice` in Go, and added cool features like:

- it's talking HTTP
- you can add a start delay to simulate a slow starting service (only the /healthz endpoint reflect that)
- you can add a delay to the answer to simulate a busy service
- you can add a number of error 500 to return before returning the real payload 

Of course, I had to update the frontend to change the call from GRPC to HTTP... At least you can base the PR on my changes...
BTW, I also cloned/updated the `frontend` as a `apiservice`, which returns JSON instead of HTML... this is to demo traffic routing between regular calls on `/` and API calls on `/api`

Check it out at https://github.com/tetratelabs/microservices-demo

**Comment by askmeegs** [comment]
Also want to add that [Bank of Anthos](https://github.com/googlecloudplatform/bank-of-anthos) is all HTTP-based, six services. 

Understanding that a major architectural update for OnlineBoutique is not in the roadmap right now, I'm going to close this issue.
