### ISSUE TITLE
Decouple release/ Manifests into Separate Files

### ISSUE THREAD

**Issue by askmeegs** [GoogleCloudPlatform/microservices-demo#375]
Reason - make the release manifests more modular for kustomize / trainings.

Mirror the structure of kubernetes-manifests/*.yaml and update the hack/ release scripts to not concatenate all the YAML resources together.

**Comment by bourgeoisor** [comment]
Started working on this here: https://github.com/GoogleCloudPlatform/microservices-demo/pull/716

Note that this might be a tough change, since a lot of external content relies on being able to do `kubectl apply -f ./release/kubernetes-manifests.yaml` (the one-file manifest)

**Comment by NimJay** [comment]
Providing an update to cool it down from our "Out of SLO" list:
This project is still on pause because we still need to think about how we'll deal with the impact this will have on tutorials/docs using Online Boutique (i.e., running `kubectl apply -f ./release/kubernetes-manifests.yaml`).

**Comment by ckim328** [comment]
Cool down for OSLO again! I believe @NimJay made some progress on this

**Comment by NimJay** [comment]
We can close this pull-request since
* [`/kustomize/base/`](https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/kustomize/base) now contains a decoupled version of [`/release/kubernetes-manifests.yaml`](https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/release/kubernetes-manifests.yaml)
* the scripts inside `/hack/` now generate the `/kustomize/base/` YAML files (when we create a new release of Online Boutique)

We have not deleted [`/release/kubernetes-manifests.yaml`](https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/release/kubernetes-manifests.yaml) yet since it's used by a lot of tutorials and demos.
We need to first update those tutorials and demos.
