### ISSUE TITLE
PermissionDeniedExceptions showing up in Error Reporting

### ISSUE THREAD

**Issue by miketruty** [GoogleCloudPlatform/microservices-demo#389]
Hi, we're using microservices-demo in some training to demo features of service mesh. We notice that there lots of PermissionDeniedException errors noted in the Cloud Console Error Reporting. They seem to be benign but users express some concern not knowing for sure. Are these related to some unfinished config where the automated load test client is sending improper requests on purpose? Can we explain this at least, and possibly disable it initially if possible? Thank you.
![Screen Shot 2020-08-26 at 8 47 26 AM](https://user-images.githubusercontent.com/2963569/91352545-9bf46680-e7af-11ea-9141-04035c188d8e.jpg)

**Comment by ahmetb** [comment]
If the application works correctly, I suspect they might be transient errors. You can hide that panel if you like. We most likely won't be able to troubleshoot this but if you would like to take a look at the logs, appreciate it. ￼

**Comment by ahmetb** [comment]
Also realistically there are probably more errors happening :) But our logging format in Python services (only 2 our of 10) is captured by Error Reporting. It could be anything (can't see the stacktrace from your screenshot) but they're most likely about how the services come up in an unordered fashion (or transient network connectivity issues on the nodes/pods).

**Comment by jwdavis** [comment]
To clarify...

- The app doesn't throw errors if you install on a non-Istio enabled GKE cluster (I used Option 3 install)
- The app throws a single error if you install on an OSS Istio enabled GKE cluster
- The errors that we are seeing are when deploying the app to an Anthos Service Mesh 1.4 enabled cluster

The cluster setup command being used is:

``
gcloud beta container clusters create ${C1_NAME} \
    --machine-type=n1-standard-4 \
    --num-nodes=2 \
    --workload-pool=${WORKLOAD_POOL} \
    --enable-stackdriver-kubernetes \
    --subnetwork=default \
    --labels mesh_id=${MESH_ID}
``

The ASM install command being used is:

``
./istio-1.4.7-asm.0/bin/istioctl manifest apply --set profile=asm \
 --set values.global.trustDomain=${WORKLOAD_POOL} \
 --set values.global.sds.token.aud=${WORKLOAD_POOL} \
 --set values.nodeagent.env.GKE_CLUSTER_URL=https://container.googleapis.com/v1/projects/${PROJECT_ID}/locations/${C1_ZONE}/clusters/${C1_NAME} 
 --set values.global.meshID=${MESH_ID} \
 --set values.global.proxy.env.GCP_METADATA="${PROJECT_ID}|${PROJECT_NUMBER}|${C1_NAME}|${C1_ZONE}" \
 --set values.tracing.enabled=true \
 --set values.global.proxy.tracer="stackdriver"
``

The errors being thrown are all permissions errors. A representative trace is attached

[stacktrace.txt](https://github.com/GoogleCloudPlatform/microservices-demo/files/5132782/stacktrace.txt)

**Comment by ahmetb** [comment]
🤔 Yep the bullet points help a lot. That suggests uploading traces to monitoring API failed. It might be that either nodes don't have enough permissions or ASM/GKE is hijacking the metadata request to provide a different access token.

Again, it still can be a timing issue about when the app container comes up vs istio-proxy sidecar container comes up. We had this class of issues in the past.

Again, this doesn't mean the error persists, it might be just that the first attempt to connect to Tracing API fails, and consecutive attempts succeed.

@askmeegs has provided some knobs in the yaml files such as DISABLE_TRACING=1 (see release/**.yaml), if you use those knobs to disable tracing, you might be able to get rid of the errors fully.

**Comment by askmeegs** [comment]
Sorry for the delay on this. I'm seeing a similar set of errors on a GKE cluster with the latest ASM v1.6 - https://cloud.google.com/service-mesh/docs/gke-install-asm 

For instance - 
```
recommendationservice-75887c55fc-hb8gn server PermissionDenied: 403 The caller does not have permission
recommendationservice-75887c55fc-hb8gn server ERROR:root:StackdriverExporter failed to emit data.Dropping 1 objects from queue.
recommendationservice-75887c55fc-hb8gn server Traceback (most recent call last):
recommendationservice-75887c55fc-hb8gn server   File "/usr/local/lib/python2.7/site-packages/opencensus/common/transports/async_.py", line 105, in _thread_main
recommendationservice-75887c55fc-hb8gn server     self.exporter.emit(data)
```

I believe the reason is because ASM requires [workload identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#enable_on_new_cluster) to be enabled in the cluster. This means that pod-to-GCP-API authentication works differently. Instead of the default GCE service account key mounted inside the pod, WI expects you to configure a GSA-to-KSA relationship from GCP IAM to your cluster, configured with granular permissions for specific APIs (eg. Cloud Trace). The pod fails to export because it doesn't have a service account key that lets it do so.   

So as Ahmet noted, one option to get rid of the errors is to simply disable Cloud Ops telemetry export across all the deployments -- 
```
        - name: DISABLE_STATS
          value: "1"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
``` 

But if you want to export metrics + traces, you'll need to set up a service account, workload identity style. For Bank of Anthos, our strategy was to [add a set of instructions for workload identity-enabled clusters](https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/master/docs/workload-identity.md). For Hipstershop, we could do the same thing.  I have a draft PR here, if you want to test the instructions.  https://github.com/GoogleCloudPlatform/microservices-demo/pull/423

**Comment by ahmetb** [comment]
Thanks for updating the instructions. Workload identity requirement seems new, I was not aware.

**Comment by mathieu-benoit** [comment]
FYI: it looks like there is a need to update the opencensus-stackdriver component to get that fix once Workload Identity is implemented: https://github.com/census-instrumentation/opencensus-python/pull/761.

**Comment by askmeegs** [comment]
Thanks for checking that Mathieu. @miketruty I'm going to close this now that we have WI instructions in this repo, feel free to reopen if you follow those steps but keep seeing problems.
