### ISSUE TITLE
Proposal: enable Discussions

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/microservices-demo#459]
New forum-like GitHub feature https://github.com/github/roadmap/issues/104, this can help users open their questions as a forum post rather than a GitHub issue and help us drive down the issue count.
Thoughts?
cc: @djmailhot @askmeegs

**Comment by askmeegs** [comment]
This is an interesting new feature - I recommend we hold off until our team chats about this re: all the GoogleCloudPlatform repos, and specifically the 10+ repos we own. I want to make sure we're being consistent and have a process set up for triage + response. 


(Context - right now Issues work well because they're mirrored into b/  so we can easily quantify closure, etc. in existing dashboards)

**Comment by askmeegs** [comment]
Closing this for now, as right now most team work happens in Github issues. Feel free to reopen if you feel strongly about adopting this feature. Thanks!
