### ISSUE TITLE
pull_request event breaks staging IP comment in forked pull requests 

### ISSUE THREAD

**Issue by askmeegs** [GoogleCloudPlatform/microservices-demo#477]
@NimJay: @askmeegs When you find time, could you please elaborate on the description here?

**Comment by Shabirmean** [comment]
> Worth mentioning: This issue sounds similar to [GoogleCloudPlatform/anthos-samples#54](https://github.com/GoogleCloudPlatform/anthos-samples/issues/54).
> The cause of the problem in [GoogleCloudPlatform/anthos-samples#54](https://github.com/GoogleCloudPlatform/anthos-samples/issues/54) was the use of GitHub secrets for environment variables.
> 
> @Shabirmean, correct me if I'm wrong (and feel free to share your thoughts). :)

This could be related to the [linked issue from anthos-samples](https://github.com/GoogleCloudPlatform/anthos-samples/issues/54). The problem there was that the *repo secrets* were not accessible in the forked repos. This issue was fixed with a workaround in this [anthos-samples PR](https://github.com/GoogleCloudPlatform/anthos-samples/pull/74). 

I'd probably check if the issue here _(staging IP comment)_ is also because of an unaccessible secret. In that case we will have to see what exactly is the secret and if it still needs to be a secret. If not we might be able to adapt the same fix as we did in the anthos-samples repo.

**Comment by bourgeoisor** [comment]
Commenting to reset OSLO. This is still something we should look at.

**Comment by donmccasland** [comment]
Commenting to reset OSLO.  @NimJay Please close if we're not going to work on this.

**Comment by minherz** [comment]
@NimJay I am closing it for now. Feel free to reopen if you need think it needs more work.
