### ISSUE TITLE
Architecture justification

### ISSUE THREAD

**Issue by joekendal** [GoogleCloudPlatform/microservices-demo#480]
There's not much in the Development  Principles on the architecture justification. I'm wondering why Google would use this approach of direct communication over an asynchronous event-driven approach with maybe a workflow engine for certain logic.

Is this standard across Google? Afaik the issues with direct communication mainly lie in having long call chains and downtime of one microservice causing all of the application to fail. The disadvantage of event-driven being added implementation complexity and eventual data consistency.

**Comment by joekendal** [comment]
@mathieu-benoit @askmeegs

**Comment by ahmetb** [comment]
Overall, this repo is meant to be a "microservices demo"; not "event driven app demo".

It is a test/demo bad for microservice-based tools, services and platforms.

One could implement an e-commerce website using many different architectures, but this format highlights the microservices/RPC aspects more, gives us a meaningful service call graph and highly meaningful distributed trace spans. 

Also it's easier to spin up nearly on any compute platform (Kubernetes, Knative, Cloud Run) because it stores no data, doesn't have dependency to any event/queue systems.
