### ISSUE TITLE
Fix Cloud Profiler in Node.js Microservices

### ISSUE THREAD

**Issue by NimJay** [GoogleCloudPlatform/microservices-demo#620]
* [Cloud Profiler](https://cloud.google.com/profiler) is used by almost all microservices:
* Here's an example of the `currencyservice` using Cloud Profiler:
https://github.com/GoogleCloudPlatform/microservices-demo/blob/884439c7437cab8d66da4657d8043278e01c33dc/src/currencyservice/server.js#L22

* The Cloud Profiler looks like the following for the `currencyservice` and `paymentservice`:
  <img width="200" alt="Screen Shot 2021-11-11 at 3 30 29 PM" src="https://user-images.githubusercontent.com/10292865/141364748-2ac1ee61-d1bf-4ac1-af47-f30427b6dc24.png">

* But it looks like the following for the other services:
  <img width="200" alt="Screen Shot 2021-11-11 at 3 28 43 PM" src="https://user-images.githubusercontent.com/10292865/141364511-94357928-c4de-4bb4-ae64-8e7a429cea35.png">

* I'm guessing our use of Cloud Profiler for the Node.js services (`currencyservice` and `paymentservice`) is currently broken, and needs to be investigated.

**Comment by Shabirmean** [comment]
Related: https://github.com/googleapis/cloud-profiler-nodejs/issues/533

**Comment by Shabirmean** [comment]
The reason we were not seeing the data for `Wall time` is because the said services are `idle` for the majority of the time. By hiding the `(idle)` stack we are able to see the stacks for the CPU usage by the rest of the progrsm.

![image](https://user-images.githubusercontent.com/7249208/143635399-c64cdb3c-f5de-4f4f-b7a0-cf78444eed21.png)
