### ISSUE TITLE
adservice: revise jvm flags for container awareness

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/microservices-demo#65]
from https://jaxenter.com/nobody-puts-java-container-139373.html:

> **Memory**
> The JVM will now consider cgroups memory limits if the following flags are specified:
>
> * -XX:+UseCGroupMemoryLimitForHeap
> * -XX:+UnlockExperimentalVMOptions
>
> In that case the Max Heap space will be automatically (if not overwritten) be set to the limit specified by the cgroup. As we discussed earlier, the JVM is using memory besides the Heap, so this will not prevent user from the OOM killer removing their containers. But, especially giving that the garbage collector will become more aggressive as the Heap fills up, this is already a great improvement.

If we start running into OOM kills in adservice, this likely would be the underlying reason. It would be good to understand and follow the best practice for this if Java isn't doing the right thing by default.

**Comment by orthros** [comment]
It has been a while since I've lived in Java-land but I'll keep my eyes on this. 

What worries me immediately after a skim of the article is that this is improved in openjdk 9 and we are currently using openjdk 8. Like I said I'm not primarily a Java dev but I wonder what the upgrade path to openjdk 9 would look like from 8. 

Lastly (also from the article) 

> Also OpenJDK 10 will improve the container support drastically: It includes, for example support for, CPU shares.

Since that article, it appears as though openjdk 10 was GA'd on [2018/03/20](http://openjdk.java.net/projects/jdk/10/). Do we want to update straight to 10?

**Comment by ahmetb** [comment]
No idea here. I opened this issue to keep the maintainers aware of a potential problem that _may_ arise someday.

**Comment by chanseokoh** [comment]
This is no longer relevant. Those flags are unnecessary with latest Java 8 releases. For example, we [removed the flags](https://github.com/GoogleContainerTools/distroless/pull/330) in Distroless after upgrading to Java 8u212. Ad Service is using `openjdk:8-slim`, which is 8u212. You can close this as obsolete.

**Comment by ahmetb** [comment]
Thanks @chanseokoh!
