### ISSUE TITLE
Switch to Kubernetes builtin grpc health checks

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/microservices-demo#662]
I recommend doing this when (1) grpc builtin health checks are in a stable Kubernetes version (2) it's been 6 months since that version is released.

Kubernetes now supports builtin grpc health checks for probes, so we can stop using the grpc-health-probe tool I wrote for this project and further cut down external dependencies. It looks like this:

```diff
@@ -44,11 +44,15 @@ spec:
         # - name: JAEGER_SERVICE_ADDR
         #   value: "jaeger-collector:14268"
         readinessProbe:
-          exec:
-            command: ["/bin/grpc_health_probe", "-addr=:3550"]
+          grpc:
+            port: 3550
         livenessProbe:
-          exec:
-            command: ["/bin/grpc_health_probe", "-addr=:3550"]
+          grpc:
+            port: 3550
         resources:
           requests:
             cpu: 100m
```

**Comment by mathieu-benoit** [comment]
This new implementation by [upstream Kubernetes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-grpc-liveness-probe) will be ideal indeed.

This feature is at the `alpha` state with Kubernetes 1.23, so it won't be yet adopted on `stable` channel yet with GKE or other managed offer ou there. [1.22 for default in `rapid` as we speak](https://cloud.google.com/kubernetes-engine/docs/release-notes).

_Note: the official doc for this feature is mentioning [`liveness probe`](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-grpc-liveness-probe) but is it working for `readiness probe` too?

_Other note: for the transition, could we have 2 `Dockerfile` files per app in order to have both container images, with or without the `grpc_health_probe` binary?_

**Comment by mathieu-benoit** [comment]
Sharing the good progress of this feature in Kubernetes upstream, with the [1.24 release](https://kubernetes.io/blog/2022/05/03/kubernetes-1-24-release-announcement/):

> With Kubernetes 1.24, the [gRPC probes functionality](https://github.com/kubernetes/enhancements/issues/2727) has entered beta and is available by default. You can now [configure startup, liveness, and readiness probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes) for your gRPC app natively within Kubernetes without exposing an HTTP endpoint or using an extra executable.

**Comment by mathieu-benoit** [comment]
Easy to do even with GKE 1.23 (alpha) like documented here: https://kubernetes.io/blog/2022/05/13/grpc-probes-now-in-beta/ :)

**Comment by mathieu-benoit** [comment]
Since [0.4.1](https://github.com/GoogleCloudPlatform/microservices-demo/releases/tag/v0.4.1) it's now an optional Online Boutique variation (i.e. a Kustomize overlay) you could leverage. See associated blog article illustrating this: https://medium.com/google-cloud/b5bd26253a4c.

**Comment by minherz** [comment]
Closing the issue because the mentioned functionality is implemented as the [native-grpc-health-check][1] kustomize component.

[1]: https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/kustomize/components/native-grpc-health-check
