### ISSUE TITLE
build [cartservice] failed: exit status 1. Docker build ran into internal error. Please retry.

### ISSUE THREAD

**Issue by TonyChiangUSA** [GoogleCloudPlatform/microservices-demo#810]
` skaffold run` failed on my laptop(MacOS/minikube v1.23.1), how to debug and fix?

**Comment by ckim328** [comment]
hi @TonyChiangUSA!
could you provide logs?

**Comment by TonyChiangUSA** [comment]
> hi @TonyChiangUSA! could you provide logs?

No more logs on the console, how to inspect it ?

**Comment by NimJay** [comment]
@TonyChiangUSA, are you able to provide details about your Mac?
1. Does it use Apple's M1 chip?
2. More specifically, what is the output you see when you run `uname -a`?
3. Also, are you sure your Docker daemon was running (e.g., press `⌘ Cmd` + `Space`, find "Docker", and open Docker before running skaffold)? When I try to use `skaffold` on my Mac without starting up Docker, I get the following error:
```
Canceled build for adservice
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?. Docker build ran into internal error. Please retry.
If this keeps happening, please open an issue..
➜  ... Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?. Docker build ran into internal error. Please retry.
If this keeps happening, please open an issue..
```
I wonder if this is the issue you faced.

**Comment by mathieu-benoit** [comment]
Hi @TonyChiangUSA, could you please give it a new try with the latest version of the `main` branch and tell us if you still have the issue? `cartservice` just got some improvements in its interaction with the `redis` database.

Could you provide the details asked by @NimJay about your local setup?

For the logs asked by @ckim328, could you run [`skaffold run --tail`](https://skaffold.dev/docs/pipeline-stages/log-tailing/) and see if there is any logs generated?

Closing this issue for now as we haven't received any complementary information from you since the last 24 days. But please, feel free to re-open it as soon as you are able to provide more details. Thanks!

**Comment by TonyChiangUSA** [comment]
Hello @mathieu-benoit , sorry for the late, still didn't work but it seems that `recommendationservice` went wrong this time. The error is `build [recommendationservice] failed: exit status 100. Docker build ran into internal error. Please retry.
If this keeps happening, please open an issue..`. As for these questions:

Does it use Apple's M1 chip? - Yes
More specifically, what is the output you see when you run uname -a? - `Darwin FrancisdeMacBook-Air.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64`
Also, are you sure your Docker daemon was running when you ran skaffold ? - I'm sure Docker is running

Version: the lastest version on `main` branch

**Comment by mathieu-benoit** [comment]
Thanks for this information, reopening this issue.

**Comment by TonyChiangUSA** [comment]
I cannot confirm that, it seems that building `cartservice ` is canceled due to the failure of building `recommendationservice `. More logs here：
`Step 2/11 : RUN apt-get update -qqy &&  apt-get -qqy install wget g++ &&        rm -rf /var/lib/apt/lists/*
 ---> Running in 2d8801caa162
E: Failed to fetch http://deb.debian.org/debian/pool/main/f/fonts-dejavu/fonts-dejavu-core_2.37-2_all.deb  502  Bad Gateway [IP: 199.232.46.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/libm/libmd/libmd0_1.0.3-3_arm64.deb  502  Bad Gateway [IP: 199.232.46.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/libp/libpng1.6/libpng16-16_1.6.37-3_arm64.deb  502  Bad Gateway [IP: 199.232.46.132 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get update -qqy &&  apt-get -qqy install wget g++ &&        rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
.......
Build [cartservice] was canceled
Building [frontend]...
Target platforms: [linux/arm64]
Build [frontend] was canceled
build [recommendationservice] failed: exit status 100. Docker build ran into internal error. Please retry.
If this keeps happening, please open an issue..
`

**Comment by mathieu-benoit** [comment]
Thanks for confirming @TonyChiangUSA. This issue is due to the fact that we don't support yet Arm64 platform. We are tracking this issue/feature request in there https://github.com/GoogleCloudPlatform/microservices-demo/issues/622.

To avoid any duplication, I'm closing this issue, but will make sure there is a reference to the one I mentioned earlier to make more evidence. Thanks for reporting this issue!

**Comment by D4ITON** [comment]
Hello I had the same issue in my Windows 11 OS, with Docker Destkop and skaffold, to solve this I tried to build the image that have the error and got the following error:

`failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = failed to parse C:\Users\myusername\.docker\.token_seed: invalid character '\x00' looking for beginning of value`


So [reviewing in internet](https://github.com/docker/buildx/issues/415#issuecomment-717319146) that error I go to Troubleshoot and 'Reset to Factory Defaults' and let me build the image with success and starts correctly the skaffold.
