### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement google-python-cloud-debugger==2.18 (from versions: none)

### ISSUE THREAD

**Issue by LisnXy** [GoogleCloudPlatform/microservices-demo#832]
### Describe the bug 
I want to deploy on my local minicube, but when I run the `skaffold run` command , at the step:
`Step 7/11 : RUN pip install -r requirements.txt`
the output shows:
```
ERROR: Could not find a version that satisfies the requirement google-python-cloud-debugger==2.18 (from versions: none)
ERROR: No matching distribution found for google-python-cloud-debugger==2.18.
```
I don't know how to handle this as a k8s beginner, and I have tried to use the v0.3.6 but it still doesn't work.
### Environment
- minikube version: v1.25.2
- Docker version 20.10.14
- macOS Monterey 12.3.1
- Apple M1 arm64

### Screenshots 

<img width="1734" alt="image" src="https://user-images.githubusercontent.com/53891402/168563936-2d17323d-e2b6-418e-8be9-50d0a6ea626f.png">

**Comment by JBHua** [comment]
I've encountered the exact same problem using Apple's M1 Chip (Mac Studio). I suspect it is either due to the chip architecture (ARM64) or macOS (see [this reply](https://github.com/GoogleCloudPlatform/cloud-debug-python/issues/20#issuecomment-638978206).)

**Comment by minherz** [comment]
It seems a duplication of #622

**Comment by mathieu-benoit** [comment]
Thanks for reporting the issue @LisnXy and thanks for confirming @JBHua. 

This issue is due to the fact that we don't support yet Arm64 platform. We are tracking this issue/feature request in there https://github.com/GoogleCloudPlatform/microservices-demo/issues/622.

To avoid any duplication, I'm closing this issue, but will make sure there is a reference to this one from the one I mentioned earlier, to make more evidence. Thanks for reporting this issue!

**Comment by swapnilwagh2204** [comment]
try installing the package by writing into the dockerfile.
example:
        RUN pip install google-python-cloud-debugger

It resolved my issue.
