### ISSUE TITLE
Error Flood when loading project in Google Cloud Editor

### ISSUE THREAD

**Issue by parawanderer** [GoogleCloudPlatform/microservices-demo#916]
### Describe the bug 
First-time user of the Cloud Platform editor. 

I was trying out the Kubernetes service, and accepted a tutorial on the topic in the UI "Google Kubernetes Engine quickstart". This tutorial brought me to the Cloud Platform editor and instructed to clone this repo into the editor. I opened the frontend main.go file and got flooded with error and warning popups, at least 20+.

I apologise if this is the wrong place to report this issue, maybe this is more of an issue with the platform itself. 
I tried to use the "feedback" drop down but when trying to take a screenshot it ended up blanking out my page (potentially due to browser extensions which I've disabled now). 

### To Reproduce 
1. Started the tutorial "Google Kubernetes Engine quickstart" from the home page
2. Created a new cluster
3. On ready, followed the tutorial by clicking the "run" button at the top of the page, opening the editor
4. Applied commands from the tutorial/sidebar into the console, cloned this repository into the editor
5. Opened the `src/frontend/main.go` file
6. Error flood started

### Logs  
N/A

### Screenshots 
![Image](https://i.imgur.com/xv49tkO.png)

![Image 2](https://i.imgur.com/L6vUz9t.png)
(These errors highlighted in the files do not resolve after waiting for at least 10 minutes)

### Environment 
Google Chrome 103.0.5060.114

### Additional context 
N/A

### Exposure 
Reloading the page and opening the editor does not consistently lead to the same flood of error popups. The highlighted red errors re: dependencies that could not be found are consistent.

**Comment by NimJay** [comment]
Thanks for reporting this issue, @parawanderer!
Thank you — especially — for being so detailed. It helps. :)

## Error 1
The errors from your first screenshot seem unrelated to Online Boutique.
```
Error while monitoring ... PersistentVolumeClaim ... gcp.go ...
```
The reason I think it's unrelated:
* There is no file titled "gcp.go" in this repo.
* Online Boutique doesn't use [PersistentVolumeClaim](https://kubernetes.io/docs/concepts/storage/persistent-volumes/)s.

The [Cloud Shell Editor's Issue Tracker](https://issuetracker.google.com/savedsearches/559766) is probably the best place to report this issue.

## Error 2
The error from your second screenshot is definitely relevant to Online Boutique.
```
could not import contrib.go.opencensus.io/exporter/jaeger (cannot find package "contrib.go.opencensus.io/exporter/jaeger" in any of 
	/usr/local/go/src/contrib.go.opencensus.io/exporter/jaeger (from $GOROOT)
	/home/nimjay/gopath/src/contrib.go.opencensus.io/exporter/jaeger (from $GOPATH)
	/google/gopath/src/contrib.go.opencensus.io/exporter/jaeger (from $GOPATH))compiler[BrokenImport](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal?utm_source%3Dgopls#BrokenImport)
```
However, these errors are expected. You can safely ignore them (when attempting any tutorial that uses Online Boutique).
They show up because we haven't run `go build` yet which will download Go dependencies for us.
But I doubt you'll find yourself needing to run `go build` anyway. Most tutorials that use Online Boutique rarely (if not, never) expect readers to build Online Boutique.
And even if you want to build Online Boutique, it's likely for development (e.g., if you want to make a change to the `/src/frontend/...` files). And during development, you'll be [using `skaffold`](https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/docs/development-guide.md) in which case building happens via Docker (see [`frontend`'s Dockerfile](https://github.com/GoogleCloudPlatform/microservices-demo/blob/release/v0.3.8/src/frontend/Dockerfile#L27)).

**Comment by parawanderer** [comment]
Ah, the second error seems very obvious now that you point it out. I'd expect behaviour like that from visual studio code running it as the regular application. Thanks for clarifying this @NimJay !

Regarding creating that issue for the first error, I am figuring I should be using the "Create Issue" button on the page you linked. Would you be able to point me to what I should choose in the "Component" field?

**Comment by sharmadhiraj86** [comment]
Can you assign this issue to me as I want to conrtibute to this project?? @NimJay @parawanderer @proppy @olegshaldybin @dazuma And if not, can you help me getting some first issues to work on as I want to contribute to open source cloud projects?

**Comment by NimJay** [comment]
First off, @sharmadhiraj86, thank you for your interest in contributing! :)
This specific issue might not be a good beginner issue since the ideal solution might need to take place in Cloud Shell Editor (closed source Google software).
But you've inspired me to label a few relatively easy GitHub issues in this repo with the ["good first issue" label](https://github.com/GoogleCloudPlatform/microservices-demo/labels/good%20first%20issue).
Let me know if you have any questions.

**Comment by minherz** [comment]
@sharmadhiraj86 I am closing this issue for now. Feel free to reopen it.
